/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) H_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[6] = {2, 2, 0, 1, 1, 0};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* H:(i0[2],i1)->(o0[2x2,1nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, *w1=w+1, *w2=w+3, w3, w4;
  const casadi_real *cs;
  /* #0: @0 = zeros(2x2,1nz) */
  w0 = 0.;
  /* #1: @1 = zeros(2x1) */
  casadi_clear(w1, 2);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 2, w2);
  /* #3: @3 = @2[0] */
  for (rr=(&w3), cs=w2+0; cs!=w2+1; cs+=1) *rr++ = *cs;
  /* #4: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #5: @3 = (@3+@4) */
  w3 += w4;
  /* #6: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #7: @3 = (-@3) */
  w3 = (- w3 );
  /* #8: (@1[0] += @3) */
  for (rr=w1+0, cs=(&w3); rr!=w1+1; rr+=1) *rr += *cs++;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), cs=w1+0; cs!=w1+1; cs+=1) *rr++ = *cs;
  /* #10: (@0[0] = @3) */
  for (rr=(&w0)+0, cs=(&w3); rr!=(&w0)+1; rr+=1) *rr = *cs++;
  /* #11: @3 = @1[0] */
  for (rr=(&w3), cs=w1+0; cs!=w1+1; cs+=1) *rr++ = *cs;
  /* #12: (@0[0] = @3) */
  for (rr=(&w0)+0, cs=(&w3); rr!=(&w0)+1; rr+=1) *rr = *cs++;
  /* #13: @3 = @0' */
  casadi_trans((&w0),casadi_s0, (&w3), casadi_s0, iw);
  /* #14: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int H(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int H_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int H_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void H_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int H_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void H_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void H_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void H_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int H_n_in(void) { return 2;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int H_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real H_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* H_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* H_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* H_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* H_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int H_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 7;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int H_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 7*sizeof(casadi_real);
  return 0;
}


