/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int H(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int H_alloc_mem(void);
extern "C" int H_init_mem(int mem);
extern "C" void H_free_mem(int mem);
extern "C" int H_checkout(void);
extern "C" void H_release(int mem);
extern "C" void H_incref(void);
extern "C" void H_decref(void);
extern "C" casadi_int H_n_in(void);
extern "C" casadi_int H_n_out(void);
extern "C" casadi_real H_default_in(casadi_int i);
extern "C" const char* H_name_in(casadi_int i);
extern "C" const char* H_name_out(casadi_int i);
extern "C" const casadi_int* H_sparsity_in(casadi_int i);
extern "C" const casadi_int* H_sparsity_out(casadi_int i);
extern "C" int H_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int H_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define H_SZ_ARG 4
#define H_SZ_RES 2
#define H_SZ_IW 3
#define H_SZ_W 7
