/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int Jx(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int Jx_alloc_mem(void);
extern "C" int Jx_init_mem(int mem);
extern "C" void Jx_free_mem(int mem);
extern "C" int Jx_checkout(void);
extern "C" void Jx_release(int mem);
extern "C" void Jx_incref(void);
extern "C" void Jx_decref(void);
extern "C" casadi_int Jx_n_in(void);
extern "C" casadi_int Jx_n_out(void);
extern "C" casadi_real Jx_default_in(casadi_int i);
extern "C" const char* Jx_name_in(casadi_int i);
extern "C" const char* Jx_name_out(casadi_int i);
extern "C" const casadi_int* Jx_sparsity_in(casadi_int i);
extern "C" const casadi_int* Jx_sparsity_out(casadi_int i);
extern "C" int Jx_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int Jx_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define Jx_SZ_ARG 4
#define Jx_SZ_RES 2
#define Jx_SZ_IW 3
#define Jx_SZ_W 6
